### ISSUE TITLE
開発環境を用意する

### ISSUE THREAD

**Issue by ykHakata** [ptsubakiq/searchb#1]
2020/10/08

- こちらの記事を参考にして `searchb` の名前でプロジェクトを作成する
- https://github.com/sakura-forest/sakura-lp/issues/1

- Pull request へのリンク: https://github.com/ptsubakiq/searchb/pull/8

**Comment by ptsubakiq** [comment]
(プロジェクトをつくるディレクトリを用意)
mkdir searchb

(開発環境は docker を活用する)
touch Dockerfile && \
echo 'FROM node:12.16.1' >> Dockerfile && \
echo 'RUN mkdir -p /usr/src/app' >> Dockerfile && \
echo 'WORKDIR /usr/src/app' >> Dockerfile

(初期のイメージを作成する)
docker build -t sample-test .

(イメージから作ったコンテナのなかで nuxt 関連のライブラリを構築)
docker run -it --rm --name ctr-sample-test -v "$PWD":/usr/src/app sample-test /bin/bash

(コンテナの中で nuxt 関連インストール実行)
yarn create nuxt-app searchb

Generating Nuxt.js project in searchb
Project name: searchb
Programming language: JavaScript
Package manager: Yarn
UI framework: Bootstrap Vue
Nuxt.js modules: Axios
Linting tools: ESLint, Prettier
Testing framework: None
Rendering mode: Single Page App
Deployment target: Static (Static/JAMStack hosting)
Development tools: jsconfig.json (Recommended for VS Code if you're not using typescript)
Continuous integration: GitHub Actions (GitHub only)
What is your GitHub username? ptsubakiq
Version control system: Git
yarn run v1.22.0

🎉  Successfully created project searchb

(インストールが終了したらdockerからはいったん抜ける)
exit

(`~/github/searchb/searchb` というディレクトリの中にできるので、階層をあげておく)
(すでに READMDE.md や .git などが存在する場合は上書きしないように注意)
(ファイル移動コマンドの例)
mv -n ~/github/searchb/searchb/* ~/github/searchb && \
mv -n ~/github/searchb/searchb/.[^\.]* ~/github/searchb

(移動元のディレクトリが空になっていることを確認)
ls -al ~/github/searchb/searchb

(不要なディレクトを削除してファイル整理終了)
rm -rf searchb

**Comment by ptsubakiq** [comment]
一通りディレクトリ構成の整理が着いたらdocker周りの設定をおこなう
```
(初期のイメージを削除)
docker image ls -a

(不要なイメージがおおくなるとpcを圧迫することになるのでまめに削除)
docker image rm sample-test

(compose コマンドのみでまかないたい、内容は下記参照)
touch docker-compose.yml

(compose の command スクリプト、実行権限が必要)
touch compose_command.bash
chmod +x compose_command.bash
```

**Comment by ptsubakiq** [comment]
- 参考コマンド
  - (docker-compose コマンドを実行するときは docker-compose.yml が存在するディレクトリで実行)

**Comment by ptsubakiq** [comment]
```
(起動中のコンテナの中に入る場合)
docker-compose exec web /bin/bash

(コンテナの中でライブラリ追加 Commander の場合)
# yarn add commander

(コンテナの外からモジュールを追加したいとき vuex-persistedstate の場合)
docker-compose exec web yarn add vuex-persistedstate
```

**Comment by ptsubakiq** [comment]
mergまで完了したのでclose
