### ISSUE TITLE
公開環境の準備

### ISSUE THREAD

**Issue by ykHakata** [ptsubakiq/searchb#2]
2020/10/08

- さくらのレンタルサーバーを公開環境にしたい
- https://www.sakura.ad.jp/
- さくらのレンタルサーバー -> スタンダード(574円)
- お申し込みをしてアカウントが所得できたことろでこのイシューは終了でよいです。
- サーバーを借りると契約情報 -> サーバ設定 -> サーバー情報の中を確認
- サーバ情報の「サーバ基本情報」と「FTP設定情報」の中身をこのイシューにコピペしておいてください
 
---
- [x] さくらインターネットのアカウントの取得
- [x] レンタルサーバ取得？する
- [x] サーバ基本情報
  - ホスト名: www4210.sakura.ne.jp
  - IPアドレス: 
IPv4: 133.242.249.150
IPv6: 2401:2500:10a:102c:133:242:249:150
  - OSバージョン: FreeBSD 11.2-RELEASE-p14 amd64
- [x] FTP設定情報
  - FTPサーバ: txsxuxbxaxkxi.sakura.ne.jp
  - FTPアカウント: txsxuxbxaxkxi
  - 初期フォルダ: www
---
- https://www.sakura.ne.jp/ でスタンダードプランでレンタルサーバを申請取得

**Comment by ptsubakiq** [comment]
@ykHakata 
さくらインターネットで申込みの際の「初期ドメイン」についてなのですが
お名前.comで取得しようとしているドメイン: txsxuxbxaxkxi.com
なので、さくらインターネットで「初期ドメイン」も同様に
https:// txsxuxbxaxkxi.sakura.ne.jp/
して方が望ましいですか。

**Comment by ptsubakiq** [comment]
レンタルサーバ取得完了

**Comment by ptsubakiq** [comment]
レンタルサーバ取得完了のためclose
