### ISSUE TITLE
ドメインを用意する

### ISSUE THREAD

**Issue by ykHakata** [ptsubakiq/searchb#3]
2020/10/08

- お名前ドットコムでオリジナルドメインを取得したい
- https://www.onamae.com/
- tsubaki.com (txsxuxbxaxkxi.workとかでも良いですか？)があればこれでいきましょう、 .com の価格が高いようなら .word など安物でも良いと思います
- ドメインは好みなので、シンプルでしっくりくるものを選んでください。
- ドメインが取得できればイシューは終了でよいです。
- 取得したドメインをこのイシューにコピペしておいてください。

---
- [x] アカウント取得
- [x] オリジナルドメイン取得
  - txsxuxbxaxkxi.work

**Comment by ptsubakiq** [comment]
ドメイン取得完了。

**Comment by ptsubakiq** [comment]
ドメイン取得完了のためclose。
