### ISSUE TITLE
github とレンタルサーバーを連携

### ISSUE THREAD

**Issue by ykHakata** [ptsubakiq/searchb#4]
2020/10/08

- github とレンタルサーバーを連携するには下記の記事を参照
- https://github.com/ykHakata/summary/blob/master/ssh_sakura.md
- github 側で公開鍵と登録する時はリポジトリごとに Settings -> Deploy keys に登録するやり方がありますからこちらの方がいいかもしれません
- さくらのレンタルサーバーに ssh で接続できたあとは `~/www/` 配下で `git clone` して `~/www/serchb/` ができる様にしてください

**Comment by ptsubakiq** [comment]
設定完了したのでclose
