### ISSUE TITLE
ドメインと公開環境を結びつける

### ISSUE THREAD

**Issue by ykHakata** [ptsubakiq/searchb#5]
2020/10/08

**さくらのレンタルサーバー側**

- 契約情報 -> サーバ設定 -> ドメイン/SSL -> ドメイン新規追加 -> 他社で取得したドメインを移管せずに使う
- txsxuxbxaxkxi.work を取得した場合は serchb.txsxuxbxaxkxi.work で登録してください
- 例) ドメイン名: serchb.txsxuxbxaxkxi.work, WEB公開フォルダ: ~/www/serchb
- 登録後にSSLの設定もする、無料で使えるSSLを選択する
- 手順の詳細はサイトの公式ドキュメントをみてください
- 登録が完了するとメールがくるはずですが、ドメイン周りの設定は時間がかかることがあります

---

**おなまえドットコム側**

- DNS -> ドメインのDNS関連機能設定 -> ドメイン名選択 -> DNSレコード設定を利用する
- 例) ホスト名: serchb.txsxuxbxaxkxi.work, TYPE: CNAME, TTL: 3600, VALUE: (ホスト名)
- 登録が完了するとメールがくるはずですが、ドメイン周りの設定は時間がかかることがあります

**Comment by ptsubakiq** [comment]
SSL化まで完了したのでclose
